### ISSUE TITLE
Can't run tests on Windows 10

### ISSUE THREAD

**Issue by Nandish47** [klamping/chester-desktop#2] opened 2018-07-31 07:13 UTC
Hi Kevin,

Chester Version: 0.1.1
OS: Windows 10
Node: v8.11.2

After installation on Windows 10, an error is seen as below when tried to run test.
![image](https://user-images.githubusercontent.com/40452994/43443292-121a74a4-94be-11e8-8b6b-169f81be61f0.png)

**Comment by klamping** [comment] 2018-07-31 16:47
Thanks for the report! Will take a look at this today.

**Comment by klamping** [comment] 2018-08-03 16:15
Still working on this. Have made some progress (identified the issue as caused by this: https://github.com/Microsoft/node-pty/issues/109) and have gotten the command to execute again... now i'm running in to an annoying path issue though. hopefully a release to fix this will be out soon.

**Comment by klamping** [comment] 2018-08-03 21:17
Can you check out release 0.1.3 to see if it fixes the issue?
https://github.com/klamping/chester-desktop/releases/tag/v0.1.3

**Comment by klamping** [comment] 2018-08-23 22:02
Closing as I believe 0.1.3 fixed this issue.

**Closed by klamping** 2018-08-23 22:02 UTC
Labels: bug
